kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-events-reader-cluster-reader
  labels:
    name: cloud-events-reader-cluster-reader
    app.kubernetes.io/name: cloud-events-reader-cluster-reader
    app.kubernetes.io/component: events-reader
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: events-reader
    namespace: logging-service
