# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Cloud containers runtime software. Possible values: docker/cri-o/containerd. In fact so far he differ docker and non-docker environments
containerRuntimeType: containerd

fluentd:
  install: true

  graylogHost: 1.2.3.4
  graylogPort: 12201

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
