# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudEventsReader:
  install: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  nodeSelectorKey: kubernetes.io/os
  nodeSelectorValue: linux
