---
name: Link Checker

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Check all markdown
          args: --base . --verbose --no-progress './**/*.md'
          # Use json as output format (instead of markdown)
          format: markdown
          # Don't fail action on broken links
          fail: false
